### ISSUE TITLE
review

### ISSUE THREAD

**Issue by wafaajaunnoo** [wafaajaunnoo/one-byte-at-a-time#1]
@saarahrahhh im going to spit out what's on my mind and you're going to tell me if it makes any sense 😌♥

**Comment by wafaajaunnoo** [comment]
@Saarahrahhh it is your time to shine :))) please i beg

**Comment by Saarahrahhh** [comment]
@wafaajaunnoo 
Your editor's note😌
#Existentialism
Para 2 Line 3
its complexities instead of "it's"
Last paragraph Line 2
learn instead of "leanr"

**Comment by wafaajaunnoo** [comment]
thank u child <3 i shall get back to it by sunday. im craving seafood pasta

**Comment by Saarahrahhh** [comment]
You're welcome Ms. Writer🫡
I'm craving meat noodles @you know where 😭

**Comment by wafaajaunnoo** [comment]
mardi 💁🏻‍♀️

**Comment by Saarahrahhh** [comment]
Mardi mo bloK beti😭🫠

**Comment by wafaajaunnoo** [comment]
okay, let us not do this here, cause what if brother Elon Musk sees this, yk
